sudo: false
language: node_js
node_js:
  - '9'
  - '8'
cache:
  directories:
    - $HOME/.npm
script: npm test

env:
  global:
    - SLACK_BOT_TOKEN=<your-slack-bot-token>
    - GITHUB_TOKEN=<your-github-token>

script:
  - npm start
